export { default as Dashboard } from './Dashboard'
export { default as Especialidades } from './Especialidades'
export { default as EspecialidadForm } from './EspecialidadForm'
export { default as CasoTable } from './CasoTable'
export { default as CasoContainer } from './CasoContainer'
export { default as Summary } from './Summary'